### PR TITLE
Attempt at #36

### PR DESCRIPTION
**Pull request by uwethuemmel**
I have made an attempt at #36 

To do so, I have done the following:

1. all keywords for CH are now combined in a json file in `keywords/keywords_ch.json`
2. the keywords for a specific index can be read using the new function `read_index_json` by giving the path to the json file and the name of the index.

In this way, we can have a good overview of all the keywords for the different indexes in a single file, and it becomes easy to add/remove keywords or to construct new indexes.

3. in `proc_trendecon_ch` for all indexes apart from the trendecon index, the keywords are now read from the json file and processing is done by `proc_index`.

## Notes
`read_index_json` depends on package `jsonlite`. I don't know where dependencies are handled.

## TODO
- [ ] take care of `jsonlite` dependency
- [ ] current version is not yet tested (in the sense that I have not checked if the indexes are properly constructed with the current version). @christophsax It would be great if you could tell me how I should do that.
- [ ] how should we handle the construction of the trendecon indicator (since the steps are different)? Should this be a separate function?
- [ ] once that is done, remove the scripts

### CODE REVIEW

**Comment by christophsax** [comment]
> how should we handle the construction of the trendecon indicator (since the steps are different)? Should this be a separate function?

The steps are only different because I constructed a non-adjusted series as well. This is not used and could be removed. See here for a blueprint: https://github.com/trendecon/trendecon/blob/master/R/proc_trendecon_de.R.

If we want to keep it, we could just call a specific function, e.g. `proc_index_trendecon_nsa()`. That's another reason why I would directly call functions: It gives you more flexibility.

**Comment by uwethuemmel** [comment]
@christophsax Thanks for your input. I will then implement it without the JSON.

Just to explain my thinking behind the JSON:

What I like about it is that it contains an overview of all keywords which go into producing indexes for a country without mixing that with the code. You write that there is nothing generalizable, but another design choice would be to just have one function which produces indexes (not country-specific) and just have country-specific JSON files (which would then also include a field for geo). In that way, all a user would have to do is create a new JSON file for a country and pass that to a single function. For users not familiar with R, that might be simpler.

**Comment by uwethuemmel** [comment]
@christophsax Sorry for bothering you with this, but I'm having trouble to make sense of the CI failure log. Could you maybe help me?

> 0 errors v | 2 warnings x | 2 notes x
> <error/rlang_error>
> Warnings found in rcmdcheck::rcmdcheck(), and `errors_on = "warning"` is set.
> Backtrace:
>   1. tic::script()
> ##[error]Error: A step failed in stage "script": script.
> Execution halted
>   2. tic::run_stage("script", stages = stages)
>   3. stage$run_all()
>   4. private$run_one(step)
>  11. step$run()
>  12. tic:::stopc("Warnings found in rcmdcheck::rcmdcheck(), ", "and `errors_on = \"warning\"` is set.")
> ##[error]Process completed with exit code 1.

Also: I have changed the signature of `proc_trendecon_ch` (removed the arguments) and now CI complains that the documentation does not match. Do I have to re-generate the documentation files by hand?

**Comment by christophsax** [comment]
You can run the tests locally:

```r
devtools::check(".")
```

This gave me:

```
❯ checking R files for non-ASCII characters ... WARNING
  Found the following file with non-ASCII characters:
    proc_trendecon_ch.R
  Portable packages must use only ASCII characters in their R code,
  except perhaps in comments.
  Use \uxxxx escapes for other characters.
```

Warnings are turned into Errors. This is about a non ASCII character in `proc_trendecon_ch.R`. I am fixing it.

**Comment by christophsax** [comment]
Die zweite Warning sollte wohl weg sein in der Zwischenzeit. Der Test schaut sich das `.Rd` file in `man` an. Er würde darum anschlagen wenn du `devtools::document()` noch nicht laufen liessest.

**Comment by christophsax** [comment]
Thanks, and sorry for the delay, again.

**Comment by christophsax** [comment]
> What I like about it is that it contains an overview of all keywords which go into producing indexes for a country without mixing that with the code. You write that there is nothing generalizable, but another design choice would be to just have one function which produces indexes (not country-specific) and just have country-specific JSON files (which would then also include a field for geo). In that way, all a user would have to do is create a new JSON file for a country and pass that to a single function. For users not familiar with R, that might be simpler.

I understand your reasoning about the JSON. If our methodology would be fully worked out, this may be fine. But we may do something slightly different for Germany and Austria, and may be happy to be able to do so in these functions.

**Pull request merged**
