### PR TITLE
Allow searches for topic codes that include slashes

### LINKED ISSUE #63: Keywords with slashes
A point made by the [OECD Weekly Tracker](http://www.oecd.org/economy/weekly-tracker-of-gdp-growth/) is that it can often be useful to work with *topics* and not raw search terms. In `gtrendsR`, search interest by topic can be retrieved using Google's topic codes ([see here](https://github.com/PMassicotte/gtrendsR/issues/321)). For example, `ts_gtrends("/m/07s_c", geo = "CH")` returns search interest for the topic unemployment and is language agnostic.

 The problem is that `proc_keyword_init("/m/07s_c", "CH")` puts the files into `raw/m/07s_c`. A relatively simple fix seems to be to:

- Change e.g. line 52 in `proc_keyword_init.R` 
```
if (indicator_raw) write_csv(d, path_draws(tolower(geo), paste0(keyword, "_d.csv")))
```
to a function call, e.g. `write_raw_keyword()` analogously to `write_keyword()` that internally calls `path_keyword()`
- Change `paste0(keyword, "_", suffix, ".csv")` in `path_keyword()` to something that takes care of slashes in `keyword`.

If this is something you think would be a suitable change to your package, I am willing to make these changes and submit a pull request.

Thanks for your great work!

### PR DESCRIPTION
**Pull request by ankargren**
This pull request fixes #63. I have used it myself now to do an index based on topic codes that include slashes, and things work fine in this regard. Two features of the pull request:

- I have added a function `remove_slash()` that takes a keyword and outputs a path friendly name. Currently, this function simply removes any slash included in the keyword. 
- I have made changes at the lowest level possible, i.e. as close as possible to writes/reads. 

Hopefully I covered everything that needs to be covered.

### CODE REVIEW

**Comment by ankargren** [comment]
I made a small additional change that will facilitate wildcard searches for categories. For example, a manual search for everything in the jobs category on Google Trends in the US is achieved here: https://trends.google.com/trends/explore?cat=60&geo=US

In `gtrendsR`, the same can be obtained by `gtrends("*", geo = "US", category = 60)`. The new commit changes `trendecon` so that wildcard searches for categories can be accomplished by e.g. `
proc_keyword_init("cat=60", "SE", from = "2012-01-01")`. Files are stored as `cat60_m.csv` and so on.

**Comment by christophsax** [comment]
@karoliskoncevicius could you review?

**Comment by karoliskoncevicius** [comment]
@christophsax I took a look at the changes, and they address the issues but I am not 100% sure about the taken approach.

1) change is made to allow the slashes within the keyword. The code is changed so that slashes are removed so the keyword "a/d" would be saved in a file named "ad". This seems a bit dangerous to me since now multiple keywords might potentially all be stored under the same file name. i.e. "keys", "k/eys", "k/e/y/s", "ke/y/s", "k/ey/s" etc.

2) second change allows searching for wildcard keywords specifying a category. It is implemented as a keyword search of the form i.e. "cat=60". What I don't like about this approach is that our function (ts_gtrends) has a separate parameter for category, so a more natural approach seems to be ts_gtrends("*", category = 60), instead of the implemented ts_gtrends("cat=60"). This would also align with original gtrends().

What do you think?

**Comment by karoliskoncevicius** [comment]
Also have to add that I don't know what a better approach for storing keywords with slashes would be. Maybe replacing them with some symbol - but not sure if using something is better than simply removing those slashes. AFAIK linux forbids having file names with slashes.

**Comment by ankargren** [comment]
@karoliskoncevicius I think you make some good points. Let me just explain why I did the way I did to provide some context for these choices:

- Removing or changing slashes could always potentially lead to collisions -- even if we'd change / to e.g. __ then if your search word was really the same but including __ then you'd get the same thing. I don't think there's any way around that. But maybe a better way would be to use something else, like __. Then "ACDC" and "AC/DC" wouldn't collide. That would only require changing `gsub("/", "", keyword)`, so that should be very easy.
- I made the category change the way I did for two reasons: to make as minor changes as possible (e.g., there's no `category` argument to `proc_keyword_init`), and because it wasn't obvious to me how something like `proc_keyword_init("*", ..., category = "20")` should be saved. For example, with this way you could combine a keyword and an open-ended category search using `proc_index(c("unemployment", "cat=20"), ...)`. If you'd get the keywords through `proc_keyword_init("*", ..., category = "20")`, I guess you'd also need something like `proc_index(c("unemployment", "*"), category = c("0", "20"), ...)` -- I guess that's not too bad actually.

**Comment by karoliskoncevicius** [comment]
@ankargren Your discovery of these two issues is a big positive. And they have to be addressed, no doubt about that. I am just thinking about the most proper way for addressing the issues without introducing more complexity. Currently my opinions are:

- Regarding removal of slashes - I wonder if maybe we can find another symbol that can be used in file names but is never/rarely used by google trends. Will have to investigate further, but would be nice if there was such a symbol (maybe "@")
- I feel that we should probably create a separate issue for this second point and spend more time on it. Currently we have some semi-working category specifications (it is used as a parameter in some places) but seems like it doesn't figure anywhere in the file name. I am not sure how important this one is. If we go with your implementation then we probably should remove those `category=` parameters from the functions to avoid further confusion.

Will think about it some more and pining @christophsax for his opinion.

**Comment by christophsax** [comment]
I think the `"cat="` is weird, I wouldn't do this.

Slashes: Why not substitute by, e.g., `-`? (Haven't thought about it, so this may obviously stupid. But it would look nice.)

**Comment by ankargren** [comment]
I think the argument for using something "ugly" is that it'd be obvious that something's been substituted. But I'm not sure how big of a problem it is anyway, since it's fairly hard to think of keywords that include a slash to begin with. Even more so if it is to be a meaningful keyword with the slash substituted for more or less any character. 

But once that is settled, should we close this and then I can submit a new PR with only the slash fix and let the category stuff wait?

**Comment by karoliskoncevicius** [comment]
I would vote strongly for the category stuff to be decoupled and placed in a separate issue. It's a broader problem and we need to figure out some of the parameters of it. In particular: 1) How are we saving same keywords from different categories - should the file names indicate category somehow? 2) What interface are we using for that? I think we should use a separate `category =` parameter here, to be consistent with gtrends.

**Comment by ankargren** [comment]
One option might be:

1. Put the category in the file name, like `recession_0_m.csv`. Predictable, informative and short.
2. Add `category` arguments to `proc_keyword` and `proc_keyword_init` (and various lower-level functions as necessary) with default `"0"`. 
3. Add `categories` (plural to follow the same `keyword`/`keywords` logic) to `proc_index` where it would have to be a vector, either with one element indicating a single category for all keywords, or of length equal to `keywords`. 

Because functions like `ts_gtrends_windows` already accept `category` as an argument, that shouldn't be too complicated to implement (unless I'm missing something).

**Comment by karoliskoncevicius** [comment]
Hello @ankargren , this was delayed for quite a while, but now the issue is being dealt with.

In short: we decided against adding category or slash support into `proc_keyword_init()` for now - since it would be a big breaking change. But we are open about reopening this issue in the future if it comes up in real-life situations.

Meanwhile, we added another function `ts_gtrends_mwd()` which gets the same data without writing it to a file. And this function accepts both: slashes, as well as searches by category alone.

Sincere Thank You for raising the issues and proposing a pull request; even if we decided to go with a slightly different implementations - it was most helpful. As a recognition for that, you are now included in to the list of trendecon contributors: https://github.com/trendecon/trendecon/commit/566781c02c093ae7ce65241d53f167e0aee45343

**Pull request closed without merging**
